### ISSUE TITLE
Migrate GitHub features to an isolated repository

### ISSUE THREAD

**Issue by gy-toxyc** [GY-CODING/.github#1]
The purpose of this issue is to migrate GitHub features (workflows, user documentation, templates) to an isolated `.github` repository.

## Tasks
- [x] Move issue templates and remove support workflow to move an issue to the Support project, as there will be an issue template for Support Tickets.
- [x] Move current deployment workflows, just leaving a reference to it from the specific project repository.
- [x] Create and move user documentation (`SECURITY.md`, ´CODE_OF_CONDUCT.md´, `CONTRIBUTING.md`).
- [x] Set up a new Pull Requests template.

<br>

In order for this issue to be closed, all tasks should be completed.
