### ISSUE TITLE
Automate Koyeb deployment for services

### ISSUE THREAD

**Issue by gy-toxyc** [GY-CODING/.github#2]
The purpose of this issue is to automate Koyeb deployment for our services, as Koyeb says they get deployed automatically after receiving a push to `master` or `main`, but it is not happening at all.

## Tasks
- [x] Develop a working workflow to deploy services. It should be general and useful by all of our services.
- [x] Call it from each repository.
- [x] Test the deployments of each service.

<br>

In order for this issue to be closed, all tasks should be completed.

**Comment by gy-toxyc** [comment]
Impossible to do through GitHub Actions due to the size of our services. And impossible to do through Koyeb as they only allow 1:1 link from their service to our GitHub organization.

**Comment by gy-toxyc** [comment]
Done integrating Koyeb public API into our GitHub Actions workflows.
